# apiVersion: cloud.google.com/v1
# kind: BackendConfig
# metadata:
#   name: health-backendconfig
#   namespace: production
# spec:
#   timeoutSec: 180
#   healthCheck:
#     checkIntervalSec: 10
#     port: 2300
#     type: HTTP
#     requestPath: /1/status/mongodb
# ---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: production
  labels:
    name: api
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    # cloud.google.com/backend-config: '{"ports": {"2300":"health-backendconfig"}}'
spec:
  type: ClusterIP
  selector:
    app: api
  ports:
    - port: 80
      targetPort: 2300
      protocol: TCP
