apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - image: gcr.io/beatlevic/bedrock-services-web
          imagePullPolicy: Always
          name: main
          # resources:
          #   limits:
          #     cpu: "1000m"
          #     memory: "4Gi"
          env:
            - name: ENV_NAME
              value: "production"
            - name: NODE_ENV
              value: "production"
            - name: DOMAIN
              value: bedrock.beatlevic.com
            - name: API_URL
              value: "https://bedrock-api.beatlevic.com"
          ports:
            - name: http-server
              containerPort: 2200
