apiVersion: v1
kind: LimitRange
metadata:
  name: staging-limit-range
  namespace: staging
spec:
  limits:
    - defaultRequest:
        cpu: 100m
        memory: 256Mi
      default:
        cpu: 1000m
        memory: 2048Mi
      type: Container
